/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TheSeatRouteImport } from './routes/the-seat'
import { Route as SectionIndexRouteImport } from './routes/$section/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AccountNewslettersRouteImport } from './routes/account/newsletters'
import { Route as SectionSubsegmentIndexRouteImport } from './routes/$section/$subsegment/index'
import { Route as SectionSubsegmentSlugRouteImport } from './routes/$section/$subsegment/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TheSeatRoute = TheSeatRouteImport.update({
  id: '/the-seat',
  path: '/the-seat',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionIndexRoute = SectionIndexRouteImport.update({
  id: '/$section/',
  path: '/$section/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountNewslettersRoute = AccountNewslettersRouteImport.update({
  id: '/account/newsletters',
  path: '/account/newsletters',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionSubsegmentIndexRoute = SectionSubsegmentIndexRouteImport.update({
  id: '/$section/$subsegment/',
  path: '/$section/$subsegment/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionSubsegmentSlugRoute = SectionSubsegmentSlugRouteImport.update({
  id: '/$section/$subsegment/$slug',
  path: '/$section/$subsegment/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/the-seat': typeof TheSeatRoute
  '/account/newsletters': typeof AccountNewslettersRoute
  '/$section/': typeof SectionIndexRoute
  '/account/': typeof AccountIndexRoute
  '/$section/$subsegment/$slug': typeof SectionSubsegmentSlugRoute
  '/$section/$subsegment/': typeof SectionSubsegmentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/the-seat': typeof TheSeatRoute
  '/account/newsletters': typeof AccountNewslettersRoute
  '/$section': typeof SectionIndexRoute
  '/account': typeof AccountIndexRoute
  '/$section/$subsegment/$slug': typeof SectionSubsegmentSlugRoute
  '/$section/$subsegment': typeof SectionSubsegmentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/the-seat': typeof TheSeatRoute
  '/account/newsletters': typeof AccountNewslettersRoute
  '/$section/': typeof SectionIndexRoute
  '/account/': typeof AccountIndexRoute
  '/$section/$subsegment/$slug': typeof SectionSubsegmentSlugRoute
  '/$section/$subsegment/': typeof SectionSubsegmentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pricing'
    | '/register'
    | '/search'
    | '/the-seat'
    | '/account/newsletters'
    | '/$section/'
    | '/account/'
    | '/$section/$subsegment/$slug'
    | '/$section/$subsegment/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pricing'
    | '/register'
    | '/search'
    | '/the-seat'
    | '/account/newsletters'
    | '/$section'
    | '/account'
    | '/$section/$subsegment/$slug'
    | '/$section/$subsegment'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/pricing'
    | '/register'
    | '/search'
    | '/the-seat'
    | '/account/newsletters'
    | '/$section/'
    | '/account/'
    | '/$section/$subsegment/$slug'
    | '/$section/$subsegment/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  TheSeatRoute: typeof TheSeatRoute
  AccountNewslettersRoute: typeof AccountNewslettersRoute
  SectionIndexRoute: typeof SectionIndexRoute
  AccountIndexRoute: typeof AccountIndexRoute
  SectionSubsegmentSlugRoute: typeof SectionSubsegmentSlugRoute
  SectionSubsegmentIndexRoute: typeof SectionSubsegmentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-seat': {
      id: '/the-seat'
      path: '/the-seat'
      fullPath: '/the-seat'
      preLoaderRoute: typeof TheSeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$section/': {
      id: '/$section/'
      path: '/$section'
      fullPath: '/$section/'
      preLoaderRoute: typeof SectionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/newsletters': {
      id: '/account/newsletters'
      path: '/account/newsletters'
      fullPath: '/account/newsletters'
      preLoaderRoute: typeof AccountNewslettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$section/$subsegment/': {
      id: '/$section/$subsegment/'
      path: '/$section/$subsegment'
      fullPath: '/$section/$subsegment/'
      preLoaderRoute: typeof SectionSubsegmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$section/$subsegment/$slug': {
      id: '/$section/$subsegment/$slug'
      path: '/$section/$subsegment/$slug'
      fullPath: '/$section/$subsegment/$slug'
      preLoaderRoute: typeof SectionSubsegmentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  TheSeatRoute: TheSeatRoute,
  AccountNewslettersRoute: AccountNewslettersRoute,
  SectionIndexRoute: SectionIndexRoute,
  AccountIndexRoute: AccountIndexRoute,
  SectionSubsegmentSlugRoute: SectionSubsegmentSlugRoute,
  SectionSubsegmentIndexRoute: SectionSubsegmentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
